dist: trusty
sudo: required
addons:
  apt:
    packages:
    - parted
    - wget
    - dosfstools
    - zip
script:
- sudo bash create-image
- xz -v -z rpizw-rover.img -c > rpizw-rover.img.xz
- zip -v rpi-base.img.zip rpi-base.img
